// Short, bilingual reading panels. Technical details live in the repository docs.
export const CONTROLS = [
  {title:['Осмотритесь','Look around'],text:['Перетаскивайте небо мышью или пальцем либо удерживайте стрелки клавиатуры: влево и вправо — обзор на 360°, вверх и вниз — высота. На компьютере подведите курсор к краю неба для плавного поворота: ближе к краю — немного быстрее. Верните курсор в центр, чтобы остановиться.','Drag with a mouse or one finger, or hold the arrow keys: left and right turn through 360°, up and down change elevation. On desktop, hover near an edge of the sky to pan gently; moving closer to the edge increases the speed. Return to the center to stop.']},
  {title:['Приблизьте небо','Take a closer look'],text:['Ползунок, колесо мыши и жест двумя пальцами плавно меняют масштаб от ×1 до ×4. Кнопки ×1, ×2 и ×4 выбирают готовое увеличение.','Use the slider, scroll wheel or pinch to zoom smoothly from ×1 to ×4. The ×1, ×2 and ×4 buttons jump to a preset.']},
  {title:['Узнайте об объекте','Explore an object'],text:['Нажмите на звезду, планету, Луну или название созвездия. Объект глубокого космоса откройте двойным нажатием; найти его по имени можно в атласе.','Select a star, planet, the Moon or a constellation name. Double-tap a deep-sky object for its card, or find it by name in the atlas.']},
  {title:['Выберите момент','Choose your moment'],text:['Установите дату и местное время. Пробел или кнопка паузы останавливают часы; скорости от ×1 до ×16 ускоряют небо и метеоры.','Set the date and local time. Space or the pause button stops the clock; speeds from ×1 to ×16 accelerate the sky and meteor events.']},
  {title:['Настройте наблюдение','Make the view your own'],text:['Включайте созвездия, метеорные потоки, эклиптику и глубокий космос. На телефоне переключатели открывает кнопка настроек вверху.','Toggle constellations, meteor showers, the ecliptic and deep sky. On a phone, open the switches with the settings button at the top.']},
  {title:['Найдите Луну','Find the Moon'],text:['Кнопка Луны показывает её фазу и положение. Если она не видна, в карточке можно выбрать подходящую ночь.','The Moon button shows its phase and position. If it is not visible, its card can take you to a suitable night.']},
  {title:['Добавьте музыку','Add music'],text:['Кнопка с нотой включает музыку из Apollo. Первая композиция — An Ending (Ascent), затем остальные семь в случайном порядке; после полного круга список перемешивается заново. Повторное нажатие выключает музыку. Стрелка рядом открывает громкость и переход к следующей композиции.','The music-note button starts the Apollo soundtrack. An Ending (Ascent) plays first, followed by the other seven tracks in random order; the collection reshuffles after each complete round. Press again to turn music off. The adjacent arrow opens volume and next-track controls.']},
  {title:['Побудьте под звёздами','Stay under the stars'],text:['Кнопка с глазом скрывает интерфейс. Верните его кнопкой в углу или клавишей Esc — и не забудьте иногда посмотреть на опушку.','The eye button hides the interface. Bring it back with the corner button or Esc — and remember to glance toward the forest.']}
];

export const FIELD_NOTES = [
  {title:['Место и время','Place and time'],text:['Площадка БТА САО РАН возле Архыза: 43.653333° N, 41.441667° E, 2070 м. Доступны 1–25 августа 2026 года; часы всегда показывают UTC+3.','The BTA observatory near Arkhyz: 43.653333° N, 41.441667° E, 2,070 m. Explore 1–25 August 2026; the clock always uses UTC+3.']},
  {title:['Звёзды и планеты','Stars and planets'],text:['Звёзды взяты из каталога HYG; Солнце, Луна и планеты рассчитаны для этой точки и выбранного времени. Проверка 459 положений по NASA JPL Horizons дала максимальное расхождение 0.263′.','Stars come from HYG; the Sun, Moon and planets are calculated for this location and time. A check of 459 positions against NASA JPL Horizons found a maximum difference of 0.263′.']},
  {title:['Видимость','What you can see'],text:['При ×1 предполагаются ясное небо и привыкшие к темноте глаза: предел около 6.5 звёздной величины. Увеличение до ×4 постепенно открывает учебный атлас до 8m. Луна и сумерки снижают видимость.','At ×1, the view assumes clear skies and dark-adapted eyes, with a limit near magnitude 6.5. Zooming toward ×4 gradually reveals an educational atlas down to magnitude 8. Moonlight and twilight reduce visibility.']},
  {title:['Созвездия и истории','Constellations and stories'],text:['88 созвездий показаны в западной традиции. Линии соединяют звёзды условно; легенды и истории названий открываются в карточках со ссылками на источники.','The 88 constellations follow the Western tradition. Their connecting lines are conventional; cards tell constellation legends and star-name histories, with links to the sources.']},
  {title:['Глубокий космос','Deep sky'],text:['В атласе — 110 объектов Мессье и 36 выбранных объектов Колдуэлла. Фотографии с авторами и лицензиями загружаются из интернета; глазом их цвета и детали выглядят иначе.','The atlas includes 110 Messier objects and 36 selected Caldwell objects. Photographs load from the internet with credits and licenses; their colors and detail differ from a visual observation.']},
  {title:['Метеорные потоки','Meteor showers'],text:['Пять потоков появляются автоматически по модели календаря IMO 2026. Частота зависит от даты, высоты радианта и лунного света. Следы немного усилены для выразительности; цвета и отдельные события — иллюстрация.','Five showers appear automatically using the IMO 2026 calendar model. Rates depend on date, radiant altitude and moonlight. Streaks are gently brightened for visibility; colors and individual events are illustrative.']},
  {title:['Млечный Путь и пейзаж','The Milky Way and landscape'],text:['Млечный Путь — адаптированная фотопанорама ESO/S. Brunier, ориентированная по небу. Лес, горы, обсерватория и их обитатели нарисованы: это художественная сцена, а не съёмка реального горизонта.','The Milky Way uses an adapted ESO/S. Brunier photographic panorama aligned with the sky. The forest, mountains, observatory and their visitors are drawn: an artistic scene rather than a surveyed horizon.']}
];

export const MODEL_NOTES = [
  'Это модель ясного неба, не запись реальной погоды или наблюдений. По умолчанию частота метеоров со всего неба собрана в текущем кадре; распределение по всему небу можно выбрать в настройках потоков. Спутники скрыты до появления подходящего архива орбит.',
  'This is a clear-sky model, not a record of actual weather or observations. By default, the all-sky meteor rate is collected in the current view; whole-sky distribution is available in the shower settings. Satellites remain hidden until suitable archived orbits are available.'
];

export const STORY_CREDITS = [
  'Истории 35 звёздных имён: пересказы и переводы All Skies Encyclopaedia — IAU-WGSN Etymology Group, Susanne M Hoffmann, Youla Azkarrula, Ian Ridpath и авторы отдельных статей; CC BY 4.0. История Нави — NASA Apollo Lunar Surface Journal. Млечный Путь: ESO/S. Brunier, CC BY 4.0, адаптация.',
  'The 35 star-name histories retell and translate All Skies Encyclopaedia by the IAU-WGSN Etymology Group, Susanne M Hoffmann, Youla Azkarrula, Ian Ridpath and individual article authors; CC BY 4.0. Navi follows NASA’s Apollo Lunar Surface Journal. Milky Way: ESO/S. Brunier, CC BY 4.0, adapted.'
];
