import {CONTROLS,FIELD_NOTES,MODEL_NOTES,STORY_CREDITS} from './field-guide.js';
import './fonts.css';
import './style.css';
import {A,D,DEFAULT,START,END,clamp,wrap,localParts,fromLocal,tickClock,moonViewingTime,vectorHorizontal,starToHorizontal} from './astro.js';
import {SkyRenderer,stars,messier,caldwell,deepSky,constellations,terrainAlt} from './renderer.js';
import {UI,pick,BODY_INFO,TYPES,DSO_TEXT,DSO_NAMES,STORIES} from './content.js';
import {parseOrbits} from './satellites.js';
import {approachZoom} from './sky-style.js';
import {STAR_STORIES} from './star-stories.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name,size=18)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.35" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${{
 sparkle:'<path d="m12 2 2.4 7.6L22 12l-7.6 2.4L12 22l-2.4-7.6L2 12l7.6-2.4Z"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4.5 4.5"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10h.01"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',pause:'<path d="M9 6v12M15 6v12"/>',play:'<path d="m8 5 11 7-11 7Z"/>',constellations:'<path d="m4 6 8 4 8-6-3 15-5-9-7 9"/><circle cx="4" cy="6" r="1.5"/><circle cx="12" cy="10" r="1.5"/><circle cx="20" cy="4" r="1.5"/><circle cx="17" cy="19" r="1.5"/>',meteors:'<path d="m7 15 12-12M10 18l11-11M4 12l8-8"/><path d="M8 16c2.5 2.5 0 6-3 5-3-1-3-4-1-6 1-1 3 0 4 1Z"/>',satellites:'<path d="m10 8 6 6-4 4-6-6Z"/><path d="m8 6 4-4 3 3-4 4m4 7 4-4 3 3-4 4M4 18l-2 4m3-6c3 0 5 2 5 5"/>',ecliptic:'<ellipse cx="12" cy="12" rx="10" ry="5" transform="rotate(-28 12 12)"/><circle cx="5" cy="15" r="2" fill="currentColor"/>',messier:'<ellipse cx="12" cy="12" rx="9" ry="4" transform="rotate(-35 12 12)"/><ellipse cx="12" cy="12" rx="5" ry="2" transform="rotate(-35 12 12)"/>',fullscreen:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',reset:'<path d="M4 10a8 8 0 1 1 1 8M4 4v6h6"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',moon:'<path d="M20 14A9 9 0 0 1 10 3 9 9 0 1 0 20 14Z"/>',sliders:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3" fill="#111c25"/><circle cx="16" cy="17" r="3" fill="#111c25"/>',mountain:'<path d="m2 19 7-12 5 7 3-4 5 9Z"/>',north:'<path d="m12 3 6 17-6-4-6 4Z"/>'}[name]||''}</svg>`;
const initialAz=matchMedia('(max-width:700px)').matches?53:45;
const state={lang:'ru',ms:DEFAULT,playing:true,speed:1,meteorScope:'view',camera:{az:initialAz,alt:22,zoom:1},layers:{constellations:true,meteors:true,satellites:false,ecliptic:false,messier:true},selected:null};
try{state.lang=localStorage.getItem('arkhyz-language')==='en'?'en':'ru';}catch{}
const t=k=>pick(UI[k]||k,state.lang);
$('#app').innerHTML=`
 <canvas id="sky" tabindex="0" aria-label="Интерактивное звёздное небо: стрелки для обзора"></canvas>
 <div class="edge-shade"></div>
 <header class="header"><a class="brand" href="#" id="brand" aria-label="Архыз"><span class="brand-symbol">${icon('sparkle',25)}</span><span>ARKHYZ<span class="brand-small">AFTER DARK</span></span></a>
 <nav><button class="nav-moon" id="moon-open" data-label="moonFind">${icon('moon')}<span data-t="moon"></span><small id="moon-percent"></small></button><button class="nav-catalog" id="catalog-open" data-label="catalog">${icon('search')}<span data-t="catalog"></span></button><button class="icon-btn" id="about-open" data-label="helpTitle">${icon('info')}</button><div class="language" aria-label="Language"><button id="lang-ru" lang="ru">RU</button><span>/</span><button id="lang-en" lang="en">EN</button></div><button class="icon-btn mobile-settings" id="mobile-settings" data-label="options">${icon('sliders')}</button></nav></header>
 <section class="intro" aria-label="Arkhyz night sky"><div class="eyebrow"><span class="small-line"></span><span data-t="subtitle"></span></div><h1 data-t="title"></h1><p data-t="place"></p><p class="intro-company" data-t="together"></p><div class="location">${icon('mountain',16)}<span data-t="height"></span></div></section>
 <aside class="sky-panel" id="sky-panel"><div class="panel-head"><span data-t="sky"></span><span class="panel-dot"></span></div><div class="layers">${['constellations','meteors','ecliptic','messier'].map(k=>`<button class="layer" data-layer="${k}" aria-pressed="${state.layers[k]}"><span class="layer-icon">${icon(k)}</span><span data-t="${k}"></span><span class="switch"></span></button>`).join('')}</div><div class="panel-note" id="panel-note"></div><button class="meteor-readout" id="meteor-about"><span class="meteor-icon">${icon('meteors',22)}</span><span><span class="meteor-heading" data-t="meteors"></span><span class="meteor-number" id="rate">—</span><span class="meteor-unit" data-t="perHour"></span></span><span class="small-arrow">↗</span></button><span class="forecast" id="meteor-auto"></span><span class="scope-note" id="scope-note"></span></aside>
 <div class="view-tools"><div class="zoom-control"><input id="zoom" type="range" min="1" max="4" step="0.01" value="1" data-label="zoom"><div class="zoom-presets" role="group" aria-label="Zoom presets"><button data-zoom="1" aria-pressed="true">×1</button><button data-zoom="2" aria-pressed="false">×2</button><button data-zoom="4" aria-pressed="false">×4</button></div></div><button class="icon-btn round" id="full" data-label="fullscreen">${icon('fullscreen')}</button><button class="icon-btn round" id="quiet" data-label="quiet">${icon('eye')}</button></div>
 <div class="bearing"><div class="compass"><span class="compass-n">N</span><div id="compass-pointer">${icon('north',23)}</div></div><div><div id="bearing-text">035° NE</div><span id="alt-text"></span></div></div>
 <div class="view-caption"><span class="view-state"><span class="live-dot"></span><span id="condition"></span><span class="caption-divider">/</span><span id="view-mode"></span></span><span class="interaction-hint" id="interaction-hint"></span></div>
 <section class="timeline" aria-label="Time controls"><div class="timeline-top"><div class="date-summary"><span class="date-num" id="date-num">12</span><span><span class="date-month" data-t="august"></span><span class="date-range">01 — 25 <span data-month-short></span></span></span></div><div class="time-summary"><span class="time-label" data-t="time"></span><time id="clock">23:00<span>:00</span></time></div><div class="playback"><button id="play" class="play-btn" data-label="pause">${icon('pause',23)}</button><div class="speeds" aria-label="Time speed">${[1,2,4,8,16].map(x=>`<button data-speed="${x}" aria-pressed="${x===1}">×${x}</button>`).join('')}</div><button class="icon-btn reset-btn" id="reset" data-label="reset">${icon('reset')}</button></div></div><div class="sliders-row"><div class="date-slider"><label for="date" data-t="date"></label><input id="date" type="range" min="1" max="25" step="1" value="12"><div class="ticks"><span>01</span><span>07</span><span>13</span><span>19</span><span>25</span></div></div><div class="time-slider"><label for="time" data-t="time"></label><input id="time" type="range" min="0" max="86399" step="1" value="82800"><div class="ticks"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>24:00</span></div></div></div></section>
 <footer class="footer"><span class="footer-coordinates"><span>43°39′12″ N</span> &nbsp; <span>41°26′30″ E</span></span><span class="footer-credit"><span data-t="inspiredLead"></span> <a href="https://astrovert.ru/" target="_blank" rel="noopener noreferrer" data-t="astrovertsBy"></a> <span>2026</span></span><button id="help-open">? <span data-t="details"></span></button></footer>
 <button id="restore" class="restore-btn" data-label="restore">${icon('eye')}<span data-t="restore"></span></button>
 <div id="toast" role="status" aria-live="polite"></div>
 <dialog id="dialog" aria-labelledby="dialog-title"><button class="dialog-close icon-btn" id="dialog-close" data-label="close">${icon('close',22)}</button><div id="dialog-content"></div></dialog><input type="file" id="orbit-file" accept=".txt,.tle,.json" hidden>
`;
let zoomTarget=1;
let renderer;let modalKind=null,lastCatalogTab='all',lastSearch='',clockLast=0;
function localize(){document.documentElement.lang=state.lang;document.title=state.lang==='ru'?'Архыз — возвращение к звёздам':'Arkhyz — back to the stars';$$('[data-t]').forEach(e=>e.textContent=t(e.dataset.t));$$('[data-label]').forEach(e=>{e.setAttribute('aria-label',t(e.dataset.label));e.title=t(e.dataset.label);});$$('[data-month-short]').forEach(e=>e.textContent=state.lang==='ru'?'АВГ':'AUG');$('#lang-ru').setAttribute('aria-pressed',state.lang==='ru');$('#lang-en').setAttribute('aria-pressed',state.lang==='en');$('#sky').setAttribute('aria-label',`${t('drag')}. ${t('arrows')}.`);$('#date').setAttribute('aria-label',t('date'));$('#time').setAttribute('aria-label',t('time'));$('#interaction-hint').textContent=matchMedia('(pointer:coarse)').matches?t('tap'):t('drag')+' · '+t('click');updateReadout();updateClock();if(modalKind==='catalog')openCatalog(false);else if(modalKind==='object'&&state.selected)showObject(state.selected,false);else if(modalKind)openText(modalKind,false);}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('shown');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('shown'),3600);}
function rangeFill(el){const pct=(el.value-el.min)/(el.max-el.min)*100;el.style.setProperty('--pct',pct+'%');}
function updateClock(){const p=localParts(state.ms),pad=v=>String(v).padStart(2,'0');$('#date-num').textContent=pad(p.day);$('#clock').innerHTML=`${pad(p.hours)}:${pad(p.minutes)}<span>:${pad(p.seconds)}</span>`;$('#clock').dateTime=new Date(state.ms).toISOString();$('#date').value=p.day;$('#time').value=p.secondOfDay;$('#time').setAttribute('aria-valuetext',`${pad(p.hours)}:${pad(p.minutes)}:${pad(p.seconds)} UTC+3`);$('#date').setAttribute('aria-valuetext',`${p.day} ${t('august')}`);rangeFill($('#date'));rangeFill($('#time'));$('#play').innerHTML=icon(state.playing?'pause':'play',23);$('#play').setAttribute('aria-label',t(state.playing?'pause':'play'));$('#play').setAttribute('aria-pressed',state.playing);}
function updateReadout(){
 if(!renderer?.frame)return;$('#moon-percent').textContent=Math.round(renderer.moon.phase*100)+'%';$('#moon-open').title=t('moon')+' · '+Math.round(renderer.moon.phase*100)+'% · '+visibility(renderer.moon);$('#meteor-auto').textContent=state.layers.meteors?(renderer.meteorCount?`${state.lang==='ru'?'Авто · метеоров':'Auto · meteors'}: ${renderer.meteorCount}`:t('forecast')):t('meteorsOff');$('#meteor-auto').title=renderer.lastMeteor?pick(renderer.lastMeteor.name,state.lang):t('forecast');$('#meteor-auto').classList.toggle('is-running',state.layers.meteors&&state.playing);$('#scope-note').textContent=t(state.meteorScope==='view'?'scopeViewNote':'scopeSkyNote');$('#rate').textContent='~ '+Math.round(renderer.shower.rate);$('#condition').textContent=renderer.sun.alt>0?t('day'):renderer.sun.alt>-18?t('twilight'):t('night');$('#view-mode').textContent=state.camera.zoom>1.02?`${t('atlas')} ×${Number(state.camera.zoom.toFixed(2)).toLocaleString(state.lang)}`:t('eye');
 const dirs=state.lang==='ru'?['С','СВ','В','ЮВ','Ю','ЮЗ','З','СЗ']:['N','NE','E','SE','S','SW','W','NW'];$('#bearing-text').textContent=`${String(Math.round(wrap(state.camera.az))).padStart(3,'0')}° ${dirs[Math.round(wrap(state.camera.az)/45)%8]}`;$('#alt-text').textContent=`${t('altitude')} ${Math.round(state.camera.alt)}°`;$('#compass-pointer').style.transform=`rotate(${-state.camera.az}deg)`;
 $('#panel-note').textContent=state.layers.satellites?(renderer.getCoverage()?`${t('satReady')} · ${renderer.getCoverage()}`:t('noOrbit')):t('conditions');$('#panel-note').classList.toggle('amber',state.layers.satellites&&!renderer.getCoverage());
 $$('[data-zoom]').forEach(b=>b.setAttribute('aria-pressed',Math.abs(+b.dataset.zoom-zoomTarget)<.015));
 $('#zoom').setAttribute('aria-valuetext',`×${Number(zoomTarget.toFixed(2)).toLocaleString(state.lang)}`);rangeFill($('#zoom'));
}
renderer=new SkyRenderer($('#sky'),state,()=>updateReadout());
function setTime(ms){state.ms=clamp(ms,START,END);renderer.lastEpoch=0;renderer.meteors=[];renderer.lastMs=state.ms;renderer.meteorClock.reset();renderer.observerDirector.reset();renderer.meteorCount=0;renderer.lastMeteor=null;updateClock();}
$('#date').addEventListener('input',e=>setTime(fromLocal(+e.target.value,localParts(state.ms).secondOfDay)));
$('#time').addEventListener('input',e=>setTime(fromLocal(localParts(state.ms).day,+e.target.value)));
$('#play').onclick=()=>{if(state.ms>=END){toast(t('end'));return;}state.playing=!state.playing;updateClock();};
$$('[data-speed]').forEach(b=>b.onclick=()=>{state.speed=+b.dataset.speed;$$('[data-speed]').forEach(e=>e.setAttribute('aria-pressed',e===b));});
$('#reset').onclick=()=>{setTime(DEFAULT);state.playing=true;state.speed=1;$$('[data-speed]').forEach(e=>e.setAttribute('aria-pressed',+e.dataset.speed===1));state.camera={az:initialAz,alt:22,zoom:1};zoomTarget=1;$('#zoom').value=1;document.body.classList.remove('exploring');updateClock();updateReadout();};
$('#brand').onclick=e=>{e.preventDefault();$('#reset').click();};
for(const lang of ['ru','en'])$('#lang-'+lang).onclick=()=>{state.lang=lang;try{localStorage.setItem('arkhyz-language',lang);}catch{}localize();};
$$('[data-layer]').forEach(b=>b.onclick=()=>{const k=b.dataset.layer;state.layers[k]=!state.layers[k];b.setAttribute('aria-pressed',state.layers[k]);if(k==='satellites'&&state.layers[k]&&!renderer.orbits.length)openText('satellites');if(k==='meteors'&&!state.layers[k])renderer.meteors=[];updateReadout();});
function setZoom(z){zoomTarget=clamp(z,1,4);$('#zoom').value=zoomTarget;if(z>1)document.body.classList.add('exploring');updateReadout();}
$('#zoom').addEventListener('input',e=>setZoom(+e.target.value));
$$('[data-zoom]').forEach(b=>b.onclick=()=>setZoom(+b.dataset.zoom));
$('#full').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();}catch{toast(state.lang==='ru'?'Полноэкранный режим недоступен в этом браузере.':'Fullscreen is not available in this browser.');}};
$('#quiet').onclick=()=>document.body.classList.add('quiet');$('#restore').onclick=()=>document.body.classList.remove('quiet');
$('#mobile-settings').onclick=()=>{const open=$('#sky-panel').classList.toggle('mobile-open');$('#mobile-settings').setAttribute('aria-expanded',open);};
const pointers=new Map();let drag=null,pinch=null,clickTimer=null,lastTap=null;
// A delayed single sky tap must not override a later control or zoom gesture.
document.addEventListener('pointerdown',e=>{if(e.target!==$('#sky')){clearTimeout(clickTimer);lastTap=null;}});
function explore(){document.body.classList.add('exploring');}
const canvas=$('#sky');
canvas.addEventListener('pointerdown',e=>{if(e.button&&e.button!==0)return;canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};if(pointers.size===2){const a=[...pointers.values()];pinch={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),zoom:state.camera.zoom};drag.moved=true;} });
canvas.addEventListener('pointermove',e=>{
 if(!pointers.has(e.pointerId)){const o=renderer.hit(e.clientX,e.clientY);canvas.style.cursor=o?'pointer':'grab';return;}
 pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
 if(pointers.size===2&&pinch){const a=[...pointers.values()];setZoom(pinch.zoom*Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)/pinch.dist);explore();return;}
 if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>5)drag.moved=true;
 if(drag.moved){state.camera.az=wrap(state.camera.az-dx/renderer.f/D);state.camera.alt=clamp(state.camera.alt+dy/renderer.f/D,-25,89.5);explore();updateReadout();}drag.x=e.clientX;drag.y=e.clientY;
});
function selectTap(x,y,isDouble){const object=renderer.hit(x,y);if(object){if(object.kind==='messier'&&!isDouble){focusObject(object);toast(state.lang==='ru'?`${object.id} · двойное нажатие — справка`:`${object.id} · double-tap for details`);}else showObject(object);return;}
 const h=vectorHorizontal(renderer.unproject(x,y));state.camera.az=h.az;state.camera.alt=clamp(h.alt,-25,89.5);setZoom(state.camera.zoom<1.5?2:state.camera.zoom<3?4:1);explore();}
canvas.addEventListener('pointerup',e=>{const moved=drag?.moved||pinch;pointers.delete(e.pointerId);if(!moved){const now=performance.now();if(lastTap&&now-lastTap.time<320&&Math.hypot(e.clientX-lastTap.x,e.clientY-lastTap.y)<24){clearTimeout(clickTimer);selectTap(e.clientX,e.clientY,true);lastTap=null;}else{lastTap={time:now,x:e.clientX,y:e.clientY};clickTimer=setTimeout(()=>selectTap(e.clientX,e.clientY,false),340);}}if(pointers.size===0){drag=null;if(pinch)pinch=null;}else{const p=[...pointers.values()][0];drag={...p,startX:p.x,startY:p.y,moved:true};}});
canvas.addEventListener('pointercancel',()=>{pointers.clear();drag=null;pinch=null;});
canvas.addEventListener('wheel',e=>{e.preventDefault();clearTimeout(clickTimer);lastTap=null;setZoom(zoomTarget*Math.exp(-clamp(e.deltaY,-240,240)*.002));explore();},{passive:false});
const keys=new Set();window.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('quiet');$('#sky-panel').classList.remove('mobile-open');}if($('#dialog').open||/INPUT|TEXTAREA|SELECT|BUTTON|A/.test(document.activeElement?.tagName))return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key)){e.preventDefault();if(e.key===' '&&!e.repeat)$('#play').click();else keys.add(e.key);explore();}if(e.key==='0'){state.camera={az:initialAz,alt:22,zoom:1};zoomTarget=1;$('#zoom').value=1;updateReadout();}});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>keys.clear());
function showDialog(kind,html,open=true){modalKind=kind;$('#dialog-content').innerHTML=html;$('#dialog').className=kind==='catalog'?'catalog-dialog':'';$('#dialog').scrollTop=0;if(open&&!$('#dialog').open)$('#dialog').showModal();}
$('#dialog-close').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#dialog').close();}});$('#dialog').addEventListener('close',()=>{modalKind=null;state.selected=null;keys.clear();});
const extLink=(url,label)=>`<a href="${escape(url)}" target="_blank" rel="noopener noreferrer" class="source-link">${escape(label)} ↗</a>`;
const infoList=items=>`<ul class="info-list">${items.map(item=>`<li><strong>${escape(pick(item.title,state.lang))}</strong><span>${escape(pick(item.text,state.lang))}</span></li>`).join('')}</ul>`;
function openText(kind,open=true){
 let title,body,extra='',eyebrow='ARKHYZ · FIELD NOTES';
 if(kind==='accuracy'){title=t('accuracy');body='';extra=`<p class="fine-print model-note">${escape(pick(MODEL_NOTES,state.lang))}</p><button class="secondary-btn" id="about-controls">${icon('info')}${t('helpTitle')}</button><details class="source-details"><summary>${t('sourcesCredits')}</summary><p class="fine-print">${escape(pick(STORY_CREDITS,state.lang))}</p><div class="source-list">${extLink('https://www.sao.ru/Doc-en/Telescopes/bta/descrip.html','САО РАН · BTA')}${extLink('https://github.com/astronexus/HYG-Database','HYG v4.1 · CC BY-SA 4.0')}${extLink('https://github.com/ofrohn/d3-celestial','D3 Celestial · BSD')}${extLink('https://github.com/mattiaverga/OpenNGC','OpenNGC · CC BY-SA 4.0')}${extLink('https://commons.wikimedia.org/wiki/Category:Messier_objects','Wikimedia Commons · Messier')}${extLink('https://aladin.cds.unistra.fr/hips/','CDS · DSS2 sky survey')}${extLink('https://www.eso.org/public/images/eso0932a/','Milky Way · ESO/S. Brunier')}${extLink('https://creativecommons.org/licenses/by/4.0/','Milky Way · CC BY 4.0 · adapted')}${extLink('https://github.com/cosinekitty/astronomy','Astronomy Engine · MIT')}${extLink('https://ssd.jpl.nasa.gov/horizons/','NASA JPL Horizons')}${extLink('https://www.imo.net/files/meteor-shower/cal2026.pdf','IMO Meteor Shower Calendar 2026')}${extLink('https://www.ianridpath.com/startales/contents.html','Ian Ridpath · Star Tales')}${extLink('https://github.com/shashwatak/satellite-js','satellite.js · MIT')}${extLink('https://exopla.net/star-names/modern-iau-star-names/','IAU WGSN · star names')}${extLink('https://ase.exopla.net/','Star histories · All Skies Encyclopaedia')}${extLink('https://creativecommons.org/licenses/by/4.0/','Star histories · CC BY 4.0 · adapted')}${extLink('https://www.nasa.gov/blogs/watch-the-skies/2023/12/05/gorgeously-green-geminids-peak-next-week/','NASA · meteor colors')}</div></details>`;}
 else if(kind==='satellites'){title=t('satTitle');body=t('satCopy')+'\n\n'+t('satCaveat');extra=`<div class="status-box">${icon('satellites',23)}<span>${renderer.orbits.length?`${t('satReady')}: ${renderer.orbits.length}<br>${renderer.getCoverage()} ${t('visible')}`:t('noOrbit')}</span></div><button class="primary-btn" id="import-orbits">${t('import')}${icon('arrow')}</button>${extLink('https://celestrak.org/NORAD/archives/request.php',t('satRequest').replace(' ↗',''))}`;}
 else if(kind==='meteors'){title=t('meteorTitle');body=t('meteorCopy')+'\n\n'+t('meteorModel')+'\n\n'+t('meteorAppearance');extra=`<div class="shower-list">${renderer.shower.showers.map(s=>`<div class="shower-row"><div><strong>${escape(pick(s.name,state.lang))}</strong><span>${t('peak')} · ${escape(pick(s.peakLabel,state.lang))}</span></div><div><strong>${s.rate<.05?'0':s.rate.toFixed(1)}</strong><span>/ ${t('hour')}</span></div></div>`).join('')}<p class="fine-print">${t('rateHere')} · ${renderer.shower.rate.toFixed(1)}</p></div><div class="meteor-scope" role="group" aria-label="${t('meteors')}"><button data-scope="view" aria-pressed="${state.meteorScope==='view'}">${t('scopeView')}</button><button data-scope="sky" aria-pressed="${state.meteorScope==='sky'}">${t('scopeSky')}</button></div><p class="fine-print">${t('scopeExplain')}</p><p class="automatic-note"><span class="live-dot"></span>${t(renderer.sun.alt>=-6?'dayMeteors':'waiting')}</p><button class="secondary-btn" id="demo-meteor">${t('demo')}${icon('meteors')}</button>${extLink('https://www.imo.net/files/meteor-shower/cal2026.pdf','IMO · 2026')}${extLink('https://www.nasa.gov/blogs/watch-the-skies/2023/12/05/gorgeously-green-geminids-peak-next-week/','NASA · meteor colors')}${extLink('https://ntrs.nasa.gov/citations/20205006958','NASA · meteor spectra')}`;}
 else{title=t('helpTitle');body='';extra=`<button class="secondary-btn" id="help-info">${icon('info')}${t('accuracy')}</button><div class="shortcut-row"><kbd>↑</kbd><kbd>←</kbd><kbd>↓</kbd><kbd>→</kbd><span>${t('arrows')}</span></div>`;}
 showDialog(kind,`<div class="dialog-eyebrow">${eyebrow}</div><h2 id="dialog-title">${title}</h2>${kind==='accuracy'?`<div class="inspiration">${extLink('https://astrovert.ru/',t('inspired'))}</div>`:''}<div class="prose">${kind==='accuracy'?infoList(FIELD_NOTES):kind==='help'?infoList(CONTROLS):escape(body).split('\n\n').map(p=>`<p>${p}</p>`).join('')}</div>${extra}`,open);
 if($('#help-info'))$('#help-info').onclick=()=>openText('accuracy',false);
 if($('#about-controls'))$('#about-controls').onclick=()=>openText('help',false);
 if(kind==='satellites')$('#import-orbits').onclick=()=>$('#orbit-file').click();
 if(kind==='meteors')$$('[data-scope]').forEach(b=>b.onclick=()=>{state.meteorScope=b.dataset.scope;$$('[data-scope]').forEach(x=>x.setAttribute('aria-pressed',x===b));updateReadout();});
 if(kind==='meteors')$('#demo-meteor').onclick=()=>{state.layers.meteors=true;$('.layer[data-layer="meteors"]').setAttribute('aria-pressed',true);if(!state.playing)state.playing=true;document.getElementById('sky-panel').classList.remove('mobile-open');document.getElementById('mobile-settings').setAttribute('aria-expanded','false');renderer.spawnMeteor(true);$('#dialog').close();toast(t('demoNote'));};
}
$('#moon-open').onclick=()=>showObject({kind:'body',id:'Moon'});
$('#about-open').onclick=()=>openText('help');$('#help-open').onclick=()=>openText('accuracy');$('#meteor-about').onclick=()=>openText('meteors');
$('#orbit-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10e6)throw new Error('tooLarge');const parsed=parseOrbits(await file.text());renderer.orbits=parsed.records;state.layers.satellites=true;$('.layer[data-layer="satellites"]')?.setAttribute('aria-pressed',true);openText('satellites',false);toast(`${t('orbitImportOk')}${parsed.records.length}. ${t('rejected')}${parsed.rejected}.`);}catch{toast(t('badOrbit'));}e.target.value='';updateReadout();};
function visibility(o){const p=renderer.getObject(o);if(!p)return t('below');return p.alt<=0?t('below'):p.alt<terrainAlt(p.az)?t('obscured'):t('above');}
function focusObject(o){const p=renderer.getObject(o);if(!p)return;if(p.alt<0){toast(t('below'));return;}state.camera.az=p.az;state.camera.alt=clamp(p.alt,-25,89.5);if(o.kind==='messier')setZoom(Math.max(2,state.camera.zoom));explore();updateReadout();}
function showObject(object,open=true){
 state.selected=object;const o=renderer.getObject(object)||object;const kind=o.kind,body=BODY_INFO[o.id],title=kind==='body'?pick(body.name,state.lang):pick(o.name,state.lang);let text='',url='',source='',historyLink='',eyebrow=t(kind),meta=[];
 const fact=(a,b)=>{if(b!==undefined&&b!==null&&b!=='')meta.push([a,b]);};
 if(kind==='body'){eyebrow=o.id==='Sun'?t('star'):o.id==='Moon'?t('moon'):t('planet');text=pick(body.text,state.lang);url=body.url||`https://science.nasa.gov/${o.id.toLowerCase()}/facts/`;source='NASA Science';fact(t('radius'),`${body.radius.toLocaleString(state.lang)} km`);fact(t('distance'),`${o.dist.toFixed(4)} AU`);fact(t('illumination'),Math.round(o.phase*100)+'%');fact(t('magnitude'),o.mag.toFixed(2));}
 else if(kind==='star'){const story=STAR_STORIES[o.id];text=story?pick(story.text,state.lang):'';historyLink=story?extLink(story.url,story.source):'';url=`https://simbad.cds.unistra.fr/simbad/sim-id?Ident=${encodeURIComponent(+o.id>0?'HIP '+o.id:o.proper||'')}`;source='SIMBAD · CDS';fact(t('distance'),o.dist<99999?`${Math.round(o.dist*3.26156).toLocaleString(state.lang)} ${t('lightYears')}`:'—');fact(t('spectral'),o.spectral||'—');fact(t('magnitude'),o.mag.toFixed(2));fact(t('constellation'),pick(constellations.find(c=>c.id===o.con)?.name||o.con,state.lang));}
 else if(kind==='messier'){eyebrow=`${o.id} · ${t('dso')}`;text=t(o.id==='M40'?'m40':o.id==='M102'?'m102':'')||'';if(!text)text=pick(DSO_TEXT[o.type]||DSO_TEXT.s,state.lang);url=(state.lang==='ru'&&o.media?.articleRu)||o.media?.article;source=t('article');fact(t('type'),pick(TYPES[o.type]||TYPES.s,state.lang));fact(t('magnitude'),o.mag);fact(t('angular'),o.dim?o.dim+'′':'—');fact('NGC / IC',o.desig);}
 else if(kind==='constellation'){eyebrow=t('legend');text=pick(STORIES[o.id]||STORIES.Ser,state.lang);url='https://www.ianridpath.com/startales/'+o.latin.toLowerCase().replaceAll(' ','')+'.html';source='Ian Ridpath · Star Tales';fact(t('constellation'),o.latin);}
 else if(kind==='satellite'){eyebrow=t('satellites');text=t('satCaveat');url=`https://celestrak.org/satcat/table-satcat.php?CATNR=${encodeURIComponent(o.id)}`;source='CelesTrak';fact('NORAD',o.id);fact(t('distance'),Math.round(o.range)+' km');fact(t('orbitAge'),o.age.toFixed(1)+' '+t('hour'));}
 fact(t('azimuth'),o.az?.toFixed(2)+'°');fact(t('altitude'),o.alt?.toFixed(2)+'°');
 const emblem=kind==='messier'?photoFigure(o):kind==='body'?(o.id==='Moon'?moonIllustration(o):`<div class="object-orb ${o.id.toLowerCase()}" style="--orb:${body.color}"></div>`):kind==='constellation'?constellationArt(o.id):`<div class="object-mark">${icon(kind==='satellite'?'satellites':'sparkle',54)}</div>`;
 const moonNote=o.id==='Moon'?`<div class="moon-note">${o.phase<.03?`<p>${t('moonNew')}</p>`:''}${o.alt<0?`<p>${t('moonBelow')}</p>`:''}<button class="secondary-btn" id="moon-night">${icon('moon')}${t('moonNight')}</button></div>`:'';
 showDialog('object',`<div class="dialog-eyebrow">${escape(eyebrow)}</div>${emblem}<h2 id="dialog-title">${escape(title)}</h2><div class="object-visibility"><span class="live-dot ${o.alt<=0?'off':''}"></span>${escape(visibility(o))}</div>${moonNote}${text?`<div class="prose"><p>${escape(text)}</p></div>`:''}<div class="facts-grid">${meta.map(([k,v])=>`<div><span>${escape(k)}</span><strong>${escape(v)}</strong></div>`).join('')}</div>${kind==='constellation'?`<p class="fine-print">${escape(t('mythNote'))}</p>`:kind==='messier'?`<p class="fine-print">${escape(t('messierNote'))}</p>`:''}<button class="primary-btn" id="focus-object" ${o.alt<0?'disabled':''}>${t('focus')}${icon('arrow')}</button>${o.media?.nasa?extLink(o.media.nasa,'NASA · Hubble'):''}${historyLink}${extLink(url,source)}`,open);
 $('#focus-object').onclick=()=>{const selected=state.selected;$('#dialog').close();focusObject(selected);state.selected=selected;};
 if(kind==='messier')loadPhoto(o);
 if(o.id==='Moon')$('#moon-night').onclick=()=>{const when=moonViewingTime(state.ms);if(when===null)return;$('#dialog').close();setTime(when);renderer.updateEphemeris();setZoom(Math.max(2,zoomTarget));focusObject({kind:'body',id:'Moon'});state.selected={kind:'body',id:'Moon'};toast(`${t('moonNightNote')} · ${localParts(when).day} ${t('august')}`);};
}
function photoCredits(photo){return `<span>${escape(photo.credit)}</span><a href="${escape(photo.page)}" target="_blank" rel="noopener noreferrer">${t(photo.survey?'surveyPhoto':'photoSource')} ↗</a><a href="${escape(photo.licenseUrl)}" target="_blank" rel="noopener noreferrer">${escape(photo.license)}</a>`;}
function photoFigure(o){const p=o.media?.photo;if(!p)return '';return `<figure class="dso-photo"><div class="photo-frame"><img id="object-photo" alt="${escape(o.id+' · '+pick(o.name,state.lang)+' · '+t('photo'))}" decoding="async" referrerpolicy="no-referrer"><span id="photo-status" role="status">${t('photoLoading')}</span><span class="photo-badge">${escape(o.id)}</span></div><figcaption id="photo-credit">${photoCredits(p)}</figcaption><p class="photo-note">${p.note?escape(pick(p.note,state.lang))+' ':''}${t('photoNote')}</p></figure>`;}
function loadPhoto(o){const img=$('#object-photo');if(!img)return;let fallback=false;const status=$('#photo-status');img.onload=()=>{img.classList.add('loaded');status.hidden=true;};img.onerror=()=>{if(!img.isConnected)return;if(!fallback&&o.media.survey.url!==img.src){fallback=true;img.src=o.media.survey.url;$('#photo-credit').innerHTML=photoCredits(o.media.survey);}else{status.textContent=t('photoError');img.hidden=true;}};img.src=o.media.photo.url;}
function moonIllustration(o){const waxing=A.MoonPhase(new Date(state.ms))<180;let points=[];for(let j=0;j<=60;j++){const y=-1+j/30;points.push([Math.sqrt(Math.max(0,1-y*y)),y]);}for(let j=60;j>=0;j--){const y=-1+j/30;points.push([(1-2*o.phase)*Math.sqrt(Math.max(0,1-y*y)),y]);}return `<div class="moon-portrait"><svg viewBox="-1.12 -1.12 2.24 2.24" role="img" aria-label="${t('illumination')} ${Math.round(o.phase*100)}%"><circle r="1" fill="#263441"/><path transform="scale(${waxing?1:-1} 1)" d="M ${points.map(p=>p.join(' ')).join(' L ')} Z" fill="#d4d9df"/></svg><span>${t(waxing?'waxing':'waning')} · ${Math.round(o.phase*100)}%</span></div>`;}
function constellationArt(id){const c=constellations.find(o=>o.id===id);let lines=renderer.constLines.find(o=>o.id===id)?.lines;if(!lines)return '';const pts=lines.flat().map(v=>vectorHorizontal(v));const center=renderer.getObject(c),coords=pts.map(p=>[wrap(p.az-center.az+180)-180,-(p.alt-center.alt)]);const x0=Math.min(...coords.map(p=>p[0])),x1=Math.max(...coords.map(p=>p[0])),y0=Math.min(...coords.map(p=>p[1])),y1=Math.max(...coords.map(p=>p[1]));const scale=Math.min(220/Math.max(x1-x0,1),85/Math.max(y1-y0,1));let index=0;return `<svg class="constellation-art" viewBox="0 0 300 120" aria-hidden="true">${lines.map(line=>{const p=line.map(()=>coords[index++]).map(p=>[150+(p[0]-(x0+x1)/2)*scale,60+(p[1]-(y0+y1)/2)*scale]);return`<polyline points="${p.map(p=>p.join(',')).join(' ')}"/>${p.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="2"/>`).join('')}`;}).join('')}</svg>`;}
const searchable=[...Object.keys(BODY_INFO).map(id=>({kind:'body',id,name:BODY_INFO[id].name})),...deepSky,...constellations.filter((c,i,a)=>a.findIndex(x=>x.id===c.id)===i),...stars.filter(s=>s.proper||s.mag<3)];
function openCatalog(open=true){showDialog('catalog',`<div class="dialog-eyebrow">110 MESSIER · 36 CALDWELL · 88 CONSTELLATIONS</div><h2 id="dialog-title">${t('catalog')}</h2><div class="catalog-search">${icon('search')}<input id="search" type="search" autocomplete="off" aria-label="${t('search')}" placeholder="${t('search')}" value="${escape(lastSearch)}"></div><div class="catalog-tabs">${['all','messier','caldwell','sso','constellations'].map(k=>`<button data-tab="${k}" aria-pressed="${lastCatalogTab===k}">${t(k==='messier'?'messierTab':k==='caldwell'?'caldwellTab':k)}</button>`).join('')}</div><div id="catalog-results" class="catalog-results"></div>`,open);$('#search').oninput=e=>{lastSearch=e.target.value;renderResults();};$$('[data-tab]').forEach(b=>b.onclick=()=>{lastCatalogTab=b.dataset.tab;$$('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',x===b));renderResults();});renderResults();if(open)setTimeout(()=>$('#search')?.focus(),50);}
function renderResults(){const query=lastSearch.toLowerCase().trim().replace(/м(?=\d)/g,'m');let list=searchable.filter(o=>(lastCatalogTab==='all'||lastCatalogTab==='messier'&&o.catalog==='Messier'||lastCatalogTab==='caldwell'&&o.catalog==='Caldwell'||lastCatalogTab==='sso'&&o.kind==='body'||lastCatalogTab==='constellations'&&o.kind==='constellation')&&(!query||[o.id,...(Array.isArray(o.name)?o.name:[o.name]),o.latin||'',o.desig||'',o.alt||'',o.aliases||''].join(' ').toLowerCase().includes(query)));
 if(lastCatalogTab==='all'&&!query)list=[...searchable.filter(x=>x.kind==='body'),...['M31','M13','M57','M45','M27','M40'].map(id=>messier.find(x=>x.id===id)),...['C20','C33','C14'].map(id=>caldwell.find(x=>x.id===id)),...constellations.filter(x=>['Cas','Per','Cyg','Lyr','And','UMa'].includes(x.id)),...stars.filter(x=>['11767','91262','102098'].includes(x.id))];
 if(query)list.sort((a,b)=>Number(b.id.toLowerCase()===query)-Number(a.id.toLowerCase()===query));
 $('#catalog-results').innerHTML=list.length?list.slice(0,160).map((o,i)=>`<button class="catalog-item" data-result="${i}"><span class="catalog-icon">${icon(o.kind==='body'?'moon':o.kind==='constellation'?'constellations':o.kind==='messier'?'messier':'sparkle',22)}</span><span><strong>${escape(pick(o.name,state.lang))}</strong><span>${escape(o.kind==='messier'?o.id+' · '+pick(TYPES[o.type],state.lang):o.kind==='body'?t('sso'):o.kind==='star'?t('star'):o.latin)}</span></span><span class="catalog-alt ${renderer.getObject(o)?.alt>0?'is-up':''}">${escape(visibility(o))}</span><span class="catalog-arrow">↗</span></button>`).join(''):`<p class="empty">${t('noResults')}</p>`;
 $$('[data-result]').forEach(b=>b.onclick=()=>showObject(list[+b.dataset.result],false));
}
$('#catalog-open').onclick=()=>openCatalog();
localize();
let lastFrame=performance.now();let lastDraw=0;
function frame(now){
 const dt=now-lastFrame;lastFrame=now;state.camera.zoom=approachZoom(state.camera.zoom,zoomTarget,Math.min(dt,100)/1000);const wasPlaying=state.playing,next=tickClock(state.ms,dt,state.speed,state.playing);state.ms=next.ms;state.playing=next.playing;if(wasPlaying&&!next.playing)toast(t('end'));
 if(keys.size){const step=Math.min(dt,100)/1000*28/state.camera.zoom;if(keys.has('ArrowLeft'))state.camera.az=wrap(state.camera.az-step);if(keys.has('ArrowRight'))state.camera.az=wrap(state.camera.az+step);if(keys.has('ArrowUp'))state.camera.alt=clamp(state.camera.alt+step,-25,89.5);if(keys.has('ArrowDown'))state.camera.alt=clamp(state.camera.alt-step,-25,89.5);}
 if(now-lastDraw>32||renderer.meteors.length){renderer.render();lastDraw=now;}
 if(now-clockLast>200){updateClock();updateReadout();clockLast=now;}
 requestAnimationFrame(frame);
}requestAnimationFrame(frame);
// Read-only diagnostics for reproducible browser verification of this local build.
Object.defineProperty(window,'arkhyzDiagnostics',{get:()=>({date:new Date(state.ms).toISOString(),local:localParts(state.ms),playing:state.playing,speed:state.speed,camera:{...state.camera},layers:{...state.layers},stars:stars.length,messier:messier.length,caldwell:caldwell.length,meteorCount:renderer.meteorCount,meteorScope:state.meteorScope,constellations:new Set(constellations.map(x=>x.id)).size,visibleStars:renderer.visibleStars,limit:renderer.limit,rate:renderer.shower?.rate,sun:renderer.sun,orbitRecords:renderer.orbits.length})});
